/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as worldFactoryV2Sol from "./WorldFactoryV2.sol";
export type { worldFactoryV2Sol };
import type * as worldRegistryV2Sol from "./WorldRegistryV2.sol";
export type { worldRegistryV2Sol };
export type { IWorldFactoryV2 } from "./IWorldFactoryV2";
export type { IWorldHook } from "./IWorldHook";
export type { IWorldProxy } from "./IWorldProxy";
export type { IWorldRegistryV2 } from "./IWorldRegistryV2";
export type { IWorldV2 } from "./IWorldV2";
export type { WorldProxy } from "./WorldProxy";
export type { WorldV2 } from "./WorldV2";
