/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type VectorAddressStruct = {
  x: string;
  y: string;
  z: string;
  t: BigNumberish;
  p: BigNumberish;
  p_sub: BigNumberish;
};

export type VectorAddressStructOutput = [
  x: string,
  y: string,
  z: string,
  t: bigint,
  p: bigint,
  p_sub: bigint
] & { x: string; y: string; z: string; t: bigint; p: bigint; p_sub: bigint };

export type WorldCreateRequestStruct = {
  owner: AddressLike;
  oldWorld: AddressLike;
  baseVector: VectorAddressStruct;
  name: string;
  initData: BytesLike;
};

export type WorldCreateRequestStructOutput = [
  owner: string,
  oldWorld: string,
  baseVector: VectorAddressStructOutput,
  name: string,
  initData: string
] & {
  owner: string;
  oldWorld: string;
  baseVector: VectorAddressStructOutput;
  name: string;
  initData: string;
};

export interface IWorldFactory0_2Interface extends Interface {
  getFunction(
    nameOrSignature: "createWorld" | "upgradeWorld"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createWorld",
    values: [WorldCreateRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeWorld",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createWorld",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeWorld",
    data: BytesLike
  ): Result;
}

export interface IWorldFactory0_2 extends BaseContract {
  connect(runner?: ContractRunner | null): IWorldFactory0_2;
  waitForDeployment(): Promise<this>;

  interface: IWorldFactory0_2Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createWorld: TypedContractMethod<
    [request: WorldCreateRequestStruct],
    [string],
    "nonpayable"
  >;

  upgradeWorld: TypedContractMethod<
    [world: AddressLike, initData: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createWorld"
  ): TypedContractMethod<
    [request: WorldCreateRequestStruct],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeWorld"
  ): TypedContractMethod<
    [world: AddressLike, initData: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
