/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AvatarFactory__factory } from "./AvatarFactory__factory";
export { INextAvatarVersion__factory } from "./INextAvatarVersion__factory";
