/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWorldRegistryV1__factory } from "./IWorldRegistryV1__factory";
export { WorldRegistryV2__factory } from "./WorldRegistryV2__factory";
