/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INextExperienceVersion,
  INextExperienceVersionInterface,
} from "../../../../contracts/experience/ExperienceFactory.sol/INextExperienceVersion";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "initData",
        type: "bytes",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INextExperienceVersion__factory {
  static readonly abi = _abi;
  static createInterface(): INextExperienceVersionInterface {
    return new Interface(_abi) as INextExperienceVersionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): INextExperienceVersion {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as INextExperienceVersion;
  }
}
