/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as portalRegistrySol from "./PortalRegistry.sol";
export type { portalRegistrySol };
export type { IBasicAvatarRegistry } from "./IBasicAvatarRegistry";
export type { IPortalCondition } from "./IPortalCondition";
export type { IPortalRegistry } from "./IPortalRegistry";
