/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  WearableLinkedList,
  WearableLinkedListInterface,
} from "../../../contracts/avatar/WearableLinkedList";

const _abi = [
  {
    inputs: [],
    name: "MAX_SIZE",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class WearableLinkedList__factory {
  static readonly abi = _abi;
  static createInterface(): WearableLinkedListInterface {
    return new Interface(_abi) as WearableLinkedListInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): WearableLinkedList {
    return new Contract(address, _abi, runner) as unknown as WearableLinkedList;
  }
}
