/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as libBaseProxySol from "./LibBaseProxy.sol";
export type { libBaseProxySol };
export type { LibAssetV1Storage } from "./LibAssetV1Storage";
export type { LibAvatarV1Storage } from "./LibAvatarV1Storage";
export type { LibExperienceV1Storage } from "./LibExperienceV1Storage";
export type { LibWorldV2Storage } from "./LibWorldV2Storage";
