/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20AssetFactory__factory } from "./ERC20AssetFactory__factory";
export { INextERC20Version__factory } from "./INextERC20Version__factory";
