/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc20AssetFactorySol from "./ERC20AssetFactory.sol";
export type { erc20AssetFactorySol };
export type { ERC20AssetRegistry } from "./ERC20AssetRegistry";
export type { NTERC20Asset } from "./NTERC20Asset";
export type { NTERC20Proxy } from "./NTERC20Proxy";
