/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAssetRegistry,
  IAssetRegistryInterface,
} from "../../../contracts/asset/IAssetRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    name: "isRegisteredAsset",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "assetType",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "initData",
        type: "bytes",
      },
    ],
    name: "registerAsset",
    outputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAssetRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetRegistryInterface {
    return new Interface(_abi) as IAssetRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAssetRegistry {
    return new Contract(address, _abi, runner) as unknown as IAssetRegistry;
  }
}
