/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LibBaseProxy__factory } from "./LibBaseProxy__factory";
export { LibProxyAccess__factory } from "./LibProxyAccess__factory";
