/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAssetConditionInterface extends Interface {
  getFunction(nameOrSignature: "canUse" | "canView"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "canUse",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canView",
    values: [AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "canUse", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canView", data: BytesLike): Result;
}

export interface IAssetCondition extends BaseContract {
  connect(runner?: ContractRunner | null): IAssetCondition;
  waitForDeployment(): Promise<this>;

  interface: IAssetConditionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  canUse: TypedContractMethod<
    [
      asset: AddressLike,
      world: AddressLike,
      company: AddressLike,
      experience: AddressLike
    ],
    [boolean],
    "view"
  >;

  canView: TypedContractMethod<
    [
      asset: AddressLike,
      world: AddressLike,
      company: AddressLike,
      experience: AddressLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "canUse"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      world: AddressLike,
      company: AddressLike,
      experience: AddressLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "canView"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      world: AddressLike,
      company: AddressLike,
      experience: AddressLike
    ],
    [boolean],
    "view"
  >;

  filters: {};
}
