/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAssetFactoryInterface extends Interface {
  getFunction(
    nameOrSignature: "createAsset" | "supportsVersion" | "upgradeAsset"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createAsset",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeAsset",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "createAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeAsset",
    data: BytesLike
  ): Result;
}

export interface IAssetFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IAssetFactory;
  waitForDeployment(): Promise<this>;

  interface: IAssetFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createAsset: TypedContractMethod<
    [initData: BytesLike],
    [string],
    "nonpayable"
  >;

  supportsVersion: TypedContractMethod<[], [bigint], "view">;

  upgradeAsset: TypedContractMethod<
    [asset: AddressLike, initData: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createAsset"
  ): TypedContractMethod<[initData: BytesLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsVersion"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "upgradeAsset"
  ): TypedContractMethod<
    [asset: AddressLike, initData: BytesLike],
    [void],
    "nonpayable"
  >;

  filters: {};
}
