/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IAssetHookInterface extends Interface {
  getFunction(
    nameOrSignature: "beforeMint" | "beforeRevoke" | "beforeTransfer"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "beforeMint",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeRevoke",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "beforeTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "beforeMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "beforeRevoke",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "beforeTransfer",
    data: BytesLike
  ): Result;
}

export interface IAssetHook extends BaseContract {
  connect(runner?: ContractRunner | null): IAssetHook;
  waitForDeployment(): Promise<this>;

  interface: IAssetHookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  beforeMint: TypedContractMethod<
    [asset: AddressLike, to: AddressLike, amtOrTokenId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  beforeRevoke: TypedContractMethod<
    [asset: AddressLike, target: AddressLike, amtOrTokenId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  beforeTransfer: TypedContractMethod<
    [asset: AddressLike, to: AddressLike, amtOrTokenId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "beforeMint"
  ): TypedContractMethod<
    [asset: AddressLike, to: AddressLike, amtOrTokenId: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeRevoke"
  ): TypedContractMethod<
    [asset: AddressLike, target: AddressLike, amtOrTokenId: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "beforeTransfer"
  ): TypedContractMethod<
    [asset: AddressLike, to: AddressLike, amtOrTokenId: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  filters: {};
}
