/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assetFactorySol from "./AssetFactory.sol";
export type { assetFactorySol };
import type * as assetRegistrySol from "./AssetRegistry.sol";
export type { assetRegistrySol };
import type * as baseAssetSol from "./BaseAsset.sol";
export type { baseAssetSol };
import type * as nonTransferableErc721AssetSol from "./NonTransferableERC721Asset.sol";
export type { nonTransferableErc721AssetSol };
import type * as sampleConditions from "./sample_conditions";
export type { sampleConditions };
export type { IAssetCondition } from "./IAssetCondition";
export type { IAssetFactory } from "./IAssetFactory";
export type { IAssetHook } from "./IAssetHook";
export type { IAssetRegistry } from "./IAssetRegistry";
export type { IERC20Asset } from "./IERC20Asset";
export type { IERC721Asset } from "./IERC721Asset";
export type { NonTransferableERC20Asset } from "./NonTransferableERC20Asset";
