/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IUpgradeMigration } from "./IUpgradeMigration";
export type { PortalRegistry } from "./PortalRegistry";
