/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export type CompanyConstructorArgsStruct = {
  companyFactory: AddressLike;
  companyRegistry: AddressLike;
  experienceRegistry: AddressLike;
  multiAssetRegistry: AddressLike;
  avatarRegistry: AddressLike;
};

export type CompanyConstructorArgsStructOutput = [
  companyFactory: string,
  companyRegistry: string,
  experienceRegistry: string,
  multiAssetRegistry: string,
  avatarRegistry: string
] & {
  companyFactory: string;
  companyRegistry: string;
  experienceRegistry: string;
  multiAssetRegistry: string;
  avatarRegistry: string;
};

export type AddExperienceArgsStruct = { name: string; initData: BytesLike };

export type AddExperienceArgsStructOutput = [name: string, initData: string] & {
  name: string;
  initData: string;
};

export type DelegatedAvatarJumpRequestStruct = {
  avatar: AddressLike;
  portalId: BigNumberish;
  agreedFee: BigNumberish;
  avatarOwnerSignature: BytesLike;
};

export type DelegatedAvatarJumpRequestStructOutput = [
  avatar: string,
  portalId: bigint,
  agreedFee: bigint,
  avatarOwnerSignature: string
] & {
  avatar: string;
  portalId: bigint;
  agreedFee: bigint;
  avatarOwnerSignature: string;
};

export type VectorAddressStruct = {
  x: string;
  y: string;
  z: string;
  t: BigNumberish;
  p: BigNumberish;
  p_sub: BigNumberish;
};

export type VectorAddressStructOutput = [
  x: string,
  y: string,
  z: string,
  t: bigint,
  p: bigint,
  p_sub: bigint
] & { x: string; y: string; z: string; t: bigint; p: bigint; p_sub: bigint };

export type CompanyInitArgsStruct = {
  owner: AddressLike;
  world: AddressLike;
  vector: VectorAddressStruct;
  initData: BytesLike;
  name: string;
};

export type CompanyInitArgsStructOutput = [
  owner: string,
  world: string,
  vector: VectorAddressStructOutput,
  initData: string,
  name: string
] & {
  owner: string;
  world: string;
  vector: VectorAddressStructOutput;
  initData: string;
  name: string;
};

export interface CompanyInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAssetCondition"
      | "addAssetHook"
      | "addExperience"
      | "addExperienceCondition"
      | "addSigners"
      | "assetRegistry"
      | "avatarRegistry"
      | "canMint"
      | "changeExperiencePortalFee"
      | "companyFactory"
      | "companyRegistry"
      | "delegateJumpForAvatar"
      | "encodeExperienceArgs"
      | "experienceRegistry"
      | "init"
      | "isSigner"
      | "mint"
      | "name"
      | "owner"
      | "removeAssetCondition"
      | "removeAssetHook"
      | "removeExperienceCondition"
      | "removeHook"
      | "removeSigners"
      | "revoke"
      | "setHook"
      | "upgrade"
      | "upgradeComplete"
      | "vectorAddress"
      | "version"
      | "withdraw"
      | "world"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetMinted"
      | "AssetRevoked"
      | "CompanyHookRemoved"
      | "CompanyHookSet"
      | "CompanyUpgraded"
      | "ExperienceAdded"
      | "ReceivedFunds"
      | "SignerAdded"
      | "SignerRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAssetCondition",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addAssetHook",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addExperience",
    values: [AddExperienceArgsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "addExperienceCondition",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addSigners",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "assetRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "avatarRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canMint",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "changeExperiencePortalFee",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "companyFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "companyRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "delegateJumpForAvatar",
    values: [DelegatedAvatarJumpRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "encodeExperienceArgs",
    values: [AddExperienceArgsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "experienceRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "init",
    values: [CompanyInitArgsStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "isSigner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAssetCondition",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAssetHook",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeExperienceCondition",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeHook",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeSigners",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "revoke",
    values: [AddressLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setHook",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "upgrade", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "upgradeComplete",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vectorAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "world", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addAssetCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addAssetHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addExperience",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addExperienceCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addSigners", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assetRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "avatarRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "changeExperiencePortalFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "companyFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "companyRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delegateJumpForAvatar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encodeExperienceArgs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "experienceRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "init", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isSigner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAssetCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAssetHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeExperienceCondition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeHook", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeSigners",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revoke", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setHook", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeComplete",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vectorAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "world", data: BytesLike): Result;
}

export namespace AssetMintedEvent {
  export type InputTuple = [
    asset: AddressLike,
    to: AddressLike,
    amountOrTokenId: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    to: string,
    amountOrTokenId: bigint
  ];
  export interface OutputObject {
    asset: string;
    to: string;
    amountOrTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssetRevokedEvent {
  export type InputTuple = [
    asset: AddressLike,
    holder: AddressLike,
    amountOrTokenId: BigNumberish
  ];
  export type OutputTuple = [
    asset: string,
    holder: string,
    amountOrTokenId: bigint
  ];
  export interface OutputObject {
    asset: string;
    holder: string;
    amountOrTokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompanyHookRemovedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompanyHookSetEvent {
  export type InputTuple = [hook: AddressLike];
  export type OutputTuple = [hook: string];
  export interface OutputObject {
    hook: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CompanyUpgradedEvent {
  export type InputTuple = [oldVersion: AddressLike, nextVersion: AddressLike];
  export type OutputTuple = [oldVersion: string, nextVersion: string];
  export interface OutputObject {
    oldVersion: string;
    nextVersion: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExperienceAddedEvent {
  export type InputTuple = [experience: AddressLike, portalId: BigNumberish];
  export type OutputTuple = [experience: string, portalId: bigint];
  export interface OutputObject {
    experience: string;
    portalId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceivedFundsEvent {
  export type InputTuple = [sender: AddressLike, value: BigNumberish];
  export type OutputTuple = [sender: string, value: bigint];
  export interface OutputObject {
    sender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerAddedEvent {
  export type InputTuple = [signer: AddressLike];
  export type OutputTuple = [signer: string];
  export interface OutputObject {
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignerRemovedEvent {
  export type InputTuple = [signer: AddressLike];
  export type OutputTuple = [signer: string];
  export interface OutputObject {
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Company extends BaseContract {
  connect(runner?: ContractRunner | null): Company;
  waitForDeployment(): Promise<this>;

  interface: CompanyInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAssetCondition: TypedContractMethod<
    [asset: AddressLike, condition: AddressLike],
    [void],
    "nonpayable"
  >;

  addAssetHook: TypedContractMethod<
    [asset: AddressLike, aHook: AddressLike],
    [void],
    "nonpayable"
  >;

  addExperience: TypedContractMethod<
    [args: AddExperienceArgsStruct],
    [void],
    "nonpayable"
  >;

  addExperienceCondition: TypedContractMethod<
    [experience: AddressLike, condition: AddressLike],
    [void],
    "nonpayable"
  >;

  addSigners: TypedContractMethod<
    [signers: AddressLike[]],
    [void],
    "nonpayable"
  >;

  assetRegistry: TypedContractMethod<[], [string], "view">;

  avatarRegistry: TypedContractMethod<[], [string], "view">;

  canMint: TypedContractMethod<
    [asset: AddressLike, to: AddressLike, extra: BytesLike],
    [boolean],
    "view"
  >;

  changeExperiencePortalFee: TypedContractMethod<
    [experience: AddressLike, fee: BigNumberish],
    [void],
    "nonpayable"
  >;

  companyFactory: TypedContractMethod<[], [string], "view">;

  companyRegistry: TypedContractMethod<[], [string], "view">;

  delegateJumpForAvatar: TypedContractMethod<
    [request: DelegatedAvatarJumpRequestStruct],
    [void],
    "nonpayable"
  >;

  encodeExperienceArgs: TypedContractMethod<
    [args: AddExperienceArgsStruct],
    [string],
    "view"
  >;

  experienceRegistry: TypedContractMethod<[], [string], "view">;

  init: TypedContractMethod<
    [request: CompanyInitArgsStruct],
    [void],
    "nonpayable"
  >;

  isSigner: TypedContractMethod<[signer: AddressLike], [boolean], "view">;

  mint: TypedContractMethod<
    [asset: AddressLike, to: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeAssetCondition: TypedContractMethod<
    [asset: AddressLike],
    [void],
    "nonpayable"
  >;

  removeAssetHook: TypedContractMethod<
    [asset: AddressLike],
    [void],
    "nonpayable"
  >;

  removeExperienceCondition: TypedContractMethod<
    [experience: AddressLike],
    [void],
    "nonpayable"
  >;

  removeHook: TypedContractMethod<[], [void], "nonpayable">;

  removeSigners: TypedContractMethod<
    [signers: AddressLike[]],
    [void],
    "nonpayable"
  >;

  revoke: TypedContractMethod<
    [asset: AddressLike, holder: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;

  setHook: TypedContractMethod<[_hook: AddressLike], [void], "nonpayable">;

  upgrade: TypedContractMethod<[initData: BytesLike], [void], "nonpayable">;

  upgradeComplete: TypedContractMethod<
    [nextVersion: AddressLike],
    [void],
    "nonpayable"
  >;

  vectorAddress: TypedContractMethod<[], [VectorAddressStructOutput], "view">;

  version: TypedContractMethod<[], [bigint], "view">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  world: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAssetCondition"
  ): TypedContractMethod<
    [asset: AddressLike, condition: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addAssetHook"
  ): TypedContractMethod<
    [asset: AddressLike, aHook: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addExperience"
  ): TypedContractMethod<[args: AddExperienceArgsStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addExperienceCondition"
  ): TypedContractMethod<
    [experience: AddressLike, condition: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addSigners"
  ): TypedContractMethod<[signers: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assetRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "avatarRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "canMint"
  ): TypedContractMethod<
    [asset: AddressLike, to: AddressLike, extra: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "changeExperiencePortalFee"
  ): TypedContractMethod<
    [experience: AddressLike, fee: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "companyFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "companyRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "delegateJumpForAvatar"
  ): TypedContractMethod<
    [request: DelegatedAvatarJumpRequestStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "encodeExperienceArgs"
  ): TypedContractMethod<[args: AddExperienceArgsStruct], [string], "view">;
  getFunction(
    nameOrSignature: "experienceRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "init"
  ): TypedContractMethod<
    [request: CompanyInitArgsStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isSigner"
  ): TypedContractMethod<[signer: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [asset: AddressLike, to: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAssetCondition"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeAssetHook"
  ): TypedContractMethod<[asset: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeExperienceCondition"
  ): TypedContractMethod<[experience: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeHook"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeSigners"
  ): TypedContractMethod<[signers: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revoke"
  ): TypedContractMethod<
    [asset: AddressLike, holder: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setHook"
  ): TypedContractMethod<[_hook: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgrade"
  ): TypedContractMethod<[initData: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeComplete"
  ): TypedContractMethod<[nextVersion: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vectorAddress"
  ): TypedContractMethod<[], [VectorAddressStructOutput], "view">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "world"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AssetMinted"
  ): TypedContractEvent<
    AssetMintedEvent.InputTuple,
    AssetMintedEvent.OutputTuple,
    AssetMintedEvent.OutputObject
  >;
  getEvent(
    key: "AssetRevoked"
  ): TypedContractEvent<
    AssetRevokedEvent.InputTuple,
    AssetRevokedEvent.OutputTuple,
    AssetRevokedEvent.OutputObject
  >;
  getEvent(
    key: "CompanyHookRemoved"
  ): TypedContractEvent<
    CompanyHookRemovedEvent.InputTuple,
    CompanyHookRemovedEvent.OutputTuple,
    CompanyHookRemovedEvent.OutputObject
  >;
  getEvent(
    key: "CompanyHookSet"
  ): TypedContractEvent<
    CompanyHookSetEvent.InputTuple,
    CompanyHookSetEvent.OutputTuple,
    CompanyHookSetEvent.OutputObject
  >;
  getEvent(
    key: "CompanyUpgraded"
  ): TypedContractEvent<
    CompanyUpgradedEvent.InputTuple,
    CompanyUpgradedEvent.OutputTuple,
    CompanyUpgradedEvent.OutputObject
  >;
  getEvent(
    key: "ExperienceAdded"
  ): TypedContractEvent<
    ExperienceAddedEvent.InputTuple,
    ExperienceAddedEvent.OutputTuple,
    ExperienceAddedEvent.OutputObject
  >;
  getEvent(
    key: "ReceivedFunds"
  ): TypedContractEvent<
    ReceivedFundsEvent.InputTuple,
    ReceivedFundsEvent.OutputTuple,
    ReceivedFundsEvent.OutputObject
  >;
  getEvent(
    key: "SignerAdded"
  ): TypedContractEvent<
    SignerAddedEvent.InputTuple,
    SignerAddedEvent.OutputTuple,
    SignerAddedEvent.OutputObject
  >;
  getEvent(
    key: "SignerRemoved"
  ): TypedContractEvent<
    SignerRemovedEvent.InputTuple,
    SignerRemovedEvent.OutputTuple,
    SignerRemovedEvent.OutputObject
  >;

  filters: {
    "AssetMinted(address,address,uint256)": TypedContractEvent<
      AssetMintedEvent.InputTuple,
      AssetMintedEvent.OutputTuple,
      AssetMintedEvent.OutputObject
    >;
    AssetMinted: TypedContractEvent<
      AssetMintedEvent.InputTuple,
      AssetMintedEvent.OutputTuple,
      AssetMintedEvent.OutputObject
    >;

    "AssetRevoked(address,address,uint256)": TypedContractEvent<
      AssetRevokedEvent.InputTuple,
      AssetRevokedEvent.OutputTuple,
      AssetRevokedEvent.OutputObject
    >;
    AssetRevoked: TypedContractEvent<
      AssetRevokedEvent.InputTuple,
      AssetRevokedEvent.OutputTuple,
      AssetRevokedEvent.OutputObject
    >;

    "CompanyHookRemoved()": TypedContractEvent<
      CompanyHookRemovedEvent.InputTuple,
      CompanyHookRemovedEvent.OutputTuple,
      CompanyHookRemovedEvent.OutputObject
    >;
    CompanyHookRemoved: TypedContractEvent<
      CompanyHookRemovedEvent.InputTuple,
      CompanyHookRemovedEvent.OutputTuple,
      CompanyHookRemovedEvent.OutputObject
    >;

    "CompanyHookSet(address)": TypedContractEvent<
      CompanyHookSetEvent.InputTuple,
      CompanyHookSetEvent.OutputTuple,
      CompanyHookSetEvent.OutputObject
    >;
    CompanyHookSet: TypedContractEvent<
      CompanyHookSetEvent.InputTuple,
      CompanyHookSetEvent.OutputTuple,
      CompanyHookSetEvent.OutputObject
    >;

    "CompanyUpgraded(address,address)": TypedContractEvent<
      CompanyUpgradedEvent.InputTuple,
      CompanyUpgradedEvent.OutputTuple,
      CompanyUpgradedEvent.OutputObject
    >;
    CompanyUpgraded: TypedContractEvent<
      CompanyUpgradedEvent.InputTuple,
      CompanyUpgradedEvent.OutputTuple,
      CompanyUpgradedEvent.OutputObject
    >;

    "ExperienceAdded(address,uint256)": TypedContractEvent<
      ExperienceAddedEvent.InputTuple,
      ExperienceAddedEvent.OutputTuple,
      ExperienceAddedEvent.OutputObject
    >;
    ExperienceAdded: TypedContractEvent<
      ExperienceAddedEvent.InputTuple,
      ExperienceAddedEvent.OutputTuple,
      ExperienceAddedEvent.OutputObject
    >;

    "ReceivedFunds(address,uint256)": TypedContractEvent<
      ReceivedFundsEvent.InputTuple,
      ReceivedFundsEvent.OutputTuple,
      ReceivedFundsEvent.OutputObject
    >;
    ReceivedFunds: TypedContractEvent<
      ReceivedFundsEvent.InputTuple,
      ReceivedFundsEvent.OutputTuple,
      ReceivedFundsEvent.OutputObject
    >;

    "SignerAdded(address)": TypedContractEvent<
      SignerAddedEvent.InputTuple,
      SignerAddedEvent.OutputTuple,
      SignerAddedEvent.OutputObject
    >;
    SignerAdded: TypedContractEvent<
      SignerAddedEvent.InputTuple,
      SignerAddedEvent.OutputTuple,
      SignerAddedEvent.OutputObject
    >;

    "SignerRemoved(address)": TypedContractEvent<
      SignerRemovedEvent.InputTuple,
      SignerRemovedEvent.OutputTuple,
      SignerRemovedEvent.OutputObject
    >;
    SignerRemoved: TypedContractEvent<
      SignerRemovedEvent.InputTuple,
      SignerRemovedEvent.OutputTuple,
      SignerRemovedEvent.OutputObject
    >;
  };
}
