/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IUpgradedERC721 } from "./IUpgradedERC721";
export type { NTERC721Asset } from "./NTERC721Asset";
