/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as experienceFactorySol from "./ExperienceFactory.sol";
export type { experienceFactorySol };
export type { Experience } from "./Experience";
export type { ExperienceProxy } from "./ExperienceProxy";
export type { ExperienceRegistry } from "./ExperienceRegistry";
export type { IBasicCompany } from "./IBasicCompany";
export type { IExperience } from "./IExperience";
export type { IExperienceFactory } from "./IExperienceFactory";
export type { IExperienceHook } from "./IExperienceHook";
export type { IExperienceRegistry } from "./IExperienceRegistry";
