/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type AvatarRegistrationRequestStruct = {
  sendTokensToAvatarOwner: boolean;
  avatarOwner: AddressLike;
  defaultExperience: AddressLike;
  username: string;
  initData: BytesLike;
};

export type AvatarRegistrationRequestStructOutput = [
  sendTokensToAvatarOwner: boolean,
  avatarOwner: string,
  defaultExperience: string,
  username: string,
  initData: string
] & {
  sendTokensToAvatarOwner: boolean;
  avatarOwner: string;
  defaultExperience: string;
  username: string;
  initData: string;
};

export interface IAvatarRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "findByUsername"
      | "isAvatar"
      | "nameAvailable"
      | "registerAvatar"
      | "setAvatarFactory"
      | "upgradeAvatar"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AvatarCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "findByUsername",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isAvatar",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nameAvailable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAvatar",
    values: [AvatarRegistrationRequestStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "setAvatarFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeAvatar",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "findByUsername",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isAvatar", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nameAvailable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAvatar",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAvatarFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeAvatar",
    data: BytesLike
  ): Result;
}

export namespace AvatarCreatedEvent {
  export type InputTuple = [
    avatar: AddressLike,
    owner: AddressLike,
    defaultExperience: AddressLike
  ];
  export type OutputTuple = [
    avatar: string,
    owner: string,
    defaultExperience: string
  ];
  export interface OutputObject {
    avatar: string;
    owner: string;
    defaultExperience: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IAvatarRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IAvatarRegistry;
  waitForDeployment(): Promise<this>;

  interface: IAvatarRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  findByUsername: TypedContractMethod<[username: string], [string], "view">;

  isAvatar: TypedContractMethod<[a: AddressLike], [boolean], "view">;

  nameAvailable: TypedContractMethod<[username: string], [boolean], "view">;

  registerAvatar: TypedContractMethod<
    [registration: AvatarRegistrationRequestStruct],
    [string],
    "payable"
  >;

  setAvatarFactory: TypedContractMethod<
    [factory: AddressLike],
    [void],
    "nonpayable"
  >;

  upgradeAvatar: TypedContractMethod<
    [initData: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "findByUsername"
  ): TypedContractMethod<[username: string], [string], "view">;
  getFunction(
    nameOrSignature: "isAvatar"
  ): TypedContractMethod<[a: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "nameAvailable"
  ): TypedContractMethod<[username: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerAvatar"
  ): TypedContractMethod<
    [registration: AvatarRegistrationRequestStruct],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "setAvatarFactory"
  ): TypedContractMethod<[factory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeAvatar"
  ): TypedContractMethod<[initData: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "AvatarCreated"
  ): TypedContractEvent<
    AvatarCreatedEvent.InputTuple,
    AvatarCreatedEvent.OutputTuple,
    AvatarCreatedEvent.OutputObject
  >;

  filters: {
    "AvatarCreated(address,address,address)": TypedContractEvent<
      AvatarCreatedEvent.InputTuple,
      AvatarCreatedEvent.OutputTuple,
      AvatarCreatedEvent.OutputObject
    >;
    AvatarCreated: TypedContractEvent<
      AvatarCreatedEvent.InputTuple,
      AvatarCreatedEvent.OutputTuple,
      AvatarCreatedEvent.OutputObject
    >;
  };
}
