/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as avatarFactorySol from "./AvatarFactory.sol";
export type { avatarFactorySol };
export type { Avatar } from "./Avatar";
export type { AvatarProxy } from "./AvatarProxy";
export type { AvatarRegistry } from "./AvatarRegistry";
export type { IAvatar } from "./IAvatar";
export type { IAvatarFactory } from "./IAvatarFactory";
export type { IAvatarHook } from "./IAvatarHook";
export type { IAvatarRegistry } from "./IAvatarRegistry";
export type { WearableLinkedList } from "./WearableLinkedList";
