/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBasicWorld__factory } from "./IBasicWorld__factory";
export { IWorld__factory } from "./IWorld__factory";
