/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface IWorldRegistryV1Interface extends Interface {
  getFunction(
    nameOrSignature: "isVectorAddressAuthority" | "isWorld"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isVectorAddressAuthority",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWorld",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "isVectorAddressAuthority",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isWorld", data: BytesLike): Result;
}

export interface IWorldRegistryV1 extends BaseContract {
  connect(runner?: ContractRunner | null): IWorldRegistryV1;
  waitForDeployment(): Promise<this>;

  interface: IWorldRegistryV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isVectorAddressAuthority: TypedContractMethod<
    [auth: AddressLike],
    [boolean],
    "view"
  >;

  isWorld: TypedContractMethod<[world: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isVectorAddressAuthority"
  ): TypedContractMethod<[auth: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWorld"
  ): TypedContractMethod<[world: AddressLike], [boolean], "view">;

  filters: {};
}
