/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AvatarRegistry__factory } from "./AvatarRegistry__factory";
export { IWorldRegistry__factory } from "./IWorldRegistry__factory";
