/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CompanyFactory__factory } from "./CompanyFactory__factory";
export { INextCompanyVersion__factory } from "./INextCompanyVersion__factory";
