/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INextCompanyVersion,
  INextCompanyVersionInterface,
} from "../../../../contracts/company/CompanyFactory.sol/INextCompanyVersion";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes",
        name: "initData",
        type: "bytes",
      },
    ],
    name: "init",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INextCompanyVersion__factory {
  static readonly abi = _abi;
  static createInterface(): INextCompanyVersionInterface {
    return new Interface(_abi) as INextCompanyVersionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): INextCompanyVersion {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as INextCompanyVersion;
  }
}
