/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AssetRegistry__factory } from "./AssetRegistry__factory";
export { IBasicAsset__factory } from "./IBasicAsset__factory";
