/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CompanyFactory } from "./CompanyFactory";
export type { INextCompanyVersion } from "./INextCompanyVersion";
