/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nterc721AssetSol from "./NTERC721Asset.sol";
export type { nterc721AssetSol };
export type { ERC721AssetFactory } from "./ERC721AssetFactory";
export type { ERC721AssetRegistry } from "./ERC721AssetRegistry";
export type { NTERC721Proxy } from "./NTERC721Proxy";
