/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IUpgradedERC721__factory } from "./IUpgradedERC721__factory";
export { NonTransferableERC721Asset__factory } from "./NonTransferableERC721Asset__factory";
